version: '3.8'
services:
  database:
    container_name: washingCar-postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.develop
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    ports:
      - 5577:5432
  pgadmin:
    container_name: washingCar-pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env.develop
    ports:
      - "5571:80"
